revised/highlighter-before/config/routes.rb
Highlighter::Application.routes.draw do
  resources :articles
  resources :snippets
  root to: 'snippets#new'
end

revised/highlighter-before/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :name
end

revised/highlighter-before/app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :code, :language, :name
end

revised/highlighter-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

revised/highlighter-before/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      redirect_to @article, notice: "Successfully created article."
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article, notice: "Successfully updated article."
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url, notice: "Successfully destroyed article."
  end
end

revised/highlighter-before/app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def index
    @snippets = Snippet.all
  end

  def show
    @snippet = Snippet.find(params[:id])
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(params[:snippet])
    if @snippet.save
      redirect_to @snippet, notice: "Snippet was successfully created."
    else
      render :new
    end
  end

  def edit
    @snippet = Snippet.find(params[:id])
  end

  def update
    @snippet = Snippet.find(params[:id])
    if @snippet.update_attributes(params[:snippet])
      redirect_to @snippet, notice: "Snippet was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy
    redirect_to snippets_url
  end
end

revised/highlighter-before/app/helpers/application_helper.rb
module ApplicationHelper
end

revised/highlighter-before/app/helpers/articles_helper.rb
module ArticlesHelper
end

revised/highlighter-before/app/helpers/snippets_helper.rb
module SnippetsHelper
end

revised/highlighter-before/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, rows: 14, cols: 50 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

revised/highlighter-before/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

revised/highlighter-before/app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">
<% @articles.each do |article| %>
  <h2><%= link_to article.name, article %></h2>
  <%= link_to "Edit", edit_article_path(article) %>
<% end %>
</div>

<%= link_to 'New Article', new_article_path %>

revised/highlighter-before/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

revised/highlighter-before/app/views/articles/show.html.erb
<h1><%= @article.name %></h1>

<%= simple_format @article.content %>

<%= link_to 'Edit', edit_article_path(@article) %>

revised/highlighter-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code Highlighter</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

revised/highlighter-before/app/views/snippets/_form.html.erb
<%= form_for @snippet do |f| %>
  <% if @snippet.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>
      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.select :language, options_for_select([["Ruby", "ruby"], ["Python", "python"], ["JavaScript", "javascript"], ["CoffeeScript", "coffeescript"], ["CSS", "css"], ["HTML", "html"]]) %>
  </div>
  <div class="field">
    <%= f.label :code, "Source Code" %><br />
    <%= f.text_area :code, rows: 14, cols: 50 %>
  </div>
  <div class="actions">
    <%= f.submit "Post Snippet" %>
  </div>
<% end %>

revised/highlighter-before/app/views/snippets/edit.html.erb
<h1>Edit Snippet</h1>

<%= render "form" %>

revised/highlighter-before/app/views/snippets/index.html.erb
<h1>Snippets</h1>

<table>
<% @snippets.each do |snippet| %>
  <tr>
    <td><%=  %></td>
    <td><%= link_to snippet.name, snippet %></td>
    <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
    <td><%= link_to 'Destroy', snippet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<p><%= link_to 'New Snippet', new_snippet_path %></p>

revised/highlighter-before/app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render "form" %>

revised/highlighter-before/app/views/snippets/show.html.erb
<h1><%= @snippet.name %></h1>

<p>
  <strong>Language:</strong>
  <%= @snippet.language.titleize %>
</p>

<pre><%= @snippet.code %></pre>

<%= link_to "Edit", edit_snippet_path(@snippet) %> |
<%= link_to "New Snippet", new_snippet_path %>